# Generated by Django 2.2.14 on 2020-07-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='updated_date',
        ),
    ]
