# Generated by Django 2.2.14 on 2020-08-25 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200721_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MaxLengthValidator(15, '15文字以内で入力してください')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, '30文字以内で入力してください')]),
        ),
    ]
